// Locality → Area Code mapping for Business Information
// Source: Kpando Municipal Assembly official area code list

export const BUSINESS_LOCALITY_AREA_MAP: Record<string, string> = {
  'Kpando Abanu (Main)': 'KpMA/KZC/ABM/',
  'Kpando Abanu (Quarters)': 'KpMA/KZC/ABQ/',
  'Kpando Abgenoxoe': 'KpMA/KZC/AGN/',
  'Kpando Agudzi': 'KpMA/KZC/AGZ/',
  'Kpando Aloyi': 'KpMA/KZC/ALY/',
  'Kpando Aloyi (Gboxome)': 'KpMA/KZC/ALG/',
  'Kpando Avetikofe': 'KpMA/KZC/AVK/',
  'Kpando Aziavi': 'KpMA/KZC/AZV/',
  'Kpando Bame': 'KpMA/KZC/BAM/',
  'Kpando BHECO': 'KpMA/KZC/BHC/',
  'Kpando Dafor': 'KpMA/KZC/DAF/',
  'Kpando Dzewoe': 'KpMA/KZC/DZW/',
  'Kpando Dzigbe': 'KpMA/KZC/DZG/',
  'Kpando Dzoanti': 'KpMA/KZC/DZT/',
  'Kpando Fesi (Atitsogse)': 'KpMA/KZC/FAG/',
  'Kpando Fesi (Avegah)': 'KpMA/KZC/FAV/',
  'Kpando Fesi (Debidiebi)': 'KpMA/KZC/FDD/',
  'Kpando Fesi (Dzakpobi)': 'KpMA/KZC/FDK/',
  'Kpando Fesi (Kpene)': 'KpMA/KZC/FKM/',
  'Kpando Fesi (Quarters)': 'KpMA/KZC/FQT/',
  'Kpando Gadza': 'KpMA/KZC/GDZ/',
  'Kpando Konda': 'KpMA/KZC/KDA/',
  'Kpando Todzi': 'KpMA/KZC/TDZ/',
  'Kpando Torkor': 'KpMA/KZC/TKR/',
  'Kpando Togorme': 'KpMA/KZC/TGM/',
  'Kpando Tsakpe (Asuto)': 'KpMA/KZC/TAT/',
  'Kpando Tsakpe (Avedza)': 'KpMA/KZC/TAV/',
  'Kpando Tsakpe (Dreveme)': 'KpMA/KZC/TDV/',
  'Kpando Tsakpe (Tsiadome)': 'KpMA/KZC/TTD/',
  'Kpando Tsakpe (Hloma)': 'KpMA/KZC/THM/',
  'Kpando Kpodzi': 'KpMA/KZC/KDZ/',
  'Kpando Tsakpe (Newtown - First Stop)': 'KpMA/KZC/TNF/',
  'Kpando Tsakpe (Newtown - Old Assemb.)': 'KpMA/KZC/TNO/',
  'Kpando Tsakpe (Newtown - Angola)': 'KpMA/KZC/TNA/',
  'Kpando Tsakpe (Newtown - Kpasae)': 'KpMA/KZC/TNK/',
  'Kpando Tsakpe (Newtown - Kpaenteh)': 'KpMA/KZC/TNT/',
  'Kpando Gabi': 'KpMA/KZC/GAB/',
  'Gbefi Hoeme': 'KpMA/GZC/HME/',
  'Gbefi Tornu': 'KpMA/GZC/TRN/',
  'Sovie Abayeme': 'KpMA/SZC/ABM/',
  'Sovie Avenu': 'KpMA/SZC/AVN/',
  'Sovie Atsame': 'KpMA/SZC/ATM/',
  'Sovie Dzavlkame': 'KpMA/SZC/DZM/',
  'Sovie Konda': 'KpMA/SZC/KDA/',
  'Sovie Kudzra': 'KpMA/SZC/KDZ/',
  'Sovie Nikorkordzi': 'KpMA/SZC/NKD/',
  'Sovie Nyamadzeanyi': 'KpMA/SZC/NDN/',
  'Sovie Tokoe': 'KpMA/SZC/TKE/',
  'Sovie Tsudzi': 'KpMA/SZC/TDZ/',
  'Kpando Zongo': 'KpMA/KZC/ZNG/',
};

export const BUSINESS_LOCALITIES = Object.keys(BUSINESS_LOCALITY_AREA_MAP) as unknown as readonly string[];
