export const LOCALITIES = [  'Kpando Abanu (Main)',  'Kpando Abanu (Quarters)',  'Kpando Abegnoxose',  'Kpando Agudzi',  'Kpando Alovi',  'Kpando Alovi (Gbosome)',  'Kpando Averikofe',  'Kpando Atavi',  'Kpando Banfe',  'Kpando BIHECO',  'Kpando Dafor',  'Kpando Dzewoe',  'Kpando Dzigbe',  'Kpando Droante',  'Kpando Fesi (Atitsogse)',  'Kpando Fesi (Avegai)',  'Kpando Fesi (Debidibi)',  'Kpando Fesi (Dzakpobi)',  'Kpando Fesi (Kpeme)',  'Kpando Fesi (Quarters)',  'Kpando Gadza',  'Kpando Konda',  'Kpando Todzi',  'Kpando Torkor',  'Kpando Togorme',  'Kpando Tsakpe (Asito)',  'Kpando Tsakpe (Aveda)',  'Kpando Tsakpe (Derveme)',  'Kpando Tsakpe (Tsadome)',  'Kpando Tsakpe (Hloma)',  'Kpando Kpodzi',  'Kpando Tsakpe (Newtown - First Stop)',  'Kpando Tsakpe (Newtown - Old Assemb.)',  'Kpando Tsakpe (Newtown - Angola)',  'Kpando Tsakpe (Newtown - Kpasce)',  'Kpando Tsakpe (Newtown - Kpaatech)',  'Kpando Gabi',  'Gbefi Hoeme',  'Gbefi Tornu',  'Sovie Abayeme',  'Sovie Avenui',  'Sovie Atsame',  'Sovie Dzawhame',  'Sovie Konda',  'Sovie Kudzra',  'Sovie Nukofikordi',  'Sovie Nyamadzeanri',  'Sovie Tokoe',  'Sovie Tudzi',  'Kpando Zongo',] as const;

export const LOCALITY_AREA_CODE_MAP: Record<string, string> = {
  'Kpando Abanu (Main)': 'KpMA/KZC/ABM',
  'Kpando Abanu (Quarters)': 'KpMA/KZC/ABQ',
  'Kpando Abegnoxose': 'KpMA/KZC/AGN',
  'Kpando Agudzi': 'KpMA/KZC/AGZ',
  'Kpando Alovi': 'KpMA/KZC/ALY',
  'Kpando Alovi (Gbosome)': 'KpMA/KZC/ALG',
  'Kpando Averikofe': 'KpMA/KZC/AVK',
  'Kpando Atavi': 'KpMA/KZC/AZV',
  'Kpando Banfe': 'KpMA/KZC/BAM',
  'Kpando BIHECO': 'KpMA/KZC/BHC',
  'Kpando Dafor': 'KpMA/KZC/DAF',
  'Kpando Dzewoe': 'KpMA/KZC/DZW',
  'Kpando Dzigbe': 'KpMA/KZC/DZG',
  'Kpando Droante': 'KpMA/KZC/DZT',
  'Kpando Fesi (Atitsogse)': 'KpMA/KZC/FAG',
  'Kpando Fesi (Avegai)': 'KpMA/KZC/FAV',
  'Kpando Fesi (Debidibi)': 'KpMA/KZC/FDD',
  'Kpando Fesi (Dzakpobi)': 'KpMA/KZC/FDK',
  'Kpando Fesi (Kpeme)': 'KpMA/KZC/FKM',
  'Kpando Fesi (Quarters)': 'KpMA/KZC/FQT',
  'Kpando Gadza': 'KpMA/KZC/GDZ',
  'Kpando Konda': 'KpMA/KZC/KDA',
  'Kpando Todzi': 'KpMA/KZC/TDZ',
  'Kpando Torkor': 'KpMA/KZC/TKR',
  'Kpando Togorme': 'KpMA/KZC/TGM',
  'Kpando Tsakpe (Asito)': 'KpMA/KZC/TAT',
  'Kpando Tsakpe (Aveda)': 'KpMA/KZC/TAV',
  'Kpando Tsakpe (Derveme)': 'KpMA/KZC/TDV',
  'Kpando Tsakpe (Tsadome)': 'KpMA/KZC/TTD',
  'Kpando Tsakpe (Hloma)': 'KpMA/KZC/THM',
  'Kpando Kpodzi': 'KpMA/KZC/KDZ',
  'Kpando Tsakpe (Newtown - First Stop)': 'KpMA/KZC/TNF',
  'Kpando Tsakpe (Newtown - Old Assemb.)': 'KpMA/KZC/TNO',
  'Kpando Tsakpe (Newtown - Angola)': 'KpMA/KZC/TNA',
  'Kpando Tsakpe (Newtown - Kpasce)': 'KpMA/KZC/TNK',
  'Kpando Tsakpe (Newtown - Kpaatech)': 'KpMA/KZC/TNT',
  'Kpando Gabi': 'KpMA/KZC/GAB',
  'Gbefi Hoeme': 'KpMA/GZC/HME',
  'Gbefi Tornu': 'KpMA/GZC/TRN',
  'Sovie Abayeme': 'KpMA/SZC/ABM',
  'Sovie Avenui': 'KpMA/SZC/AVN',
  'Sovie Atsame': 'KpMA/SZC/ATM',
  'Sovie Dzawhame': 'KpMA/SZC/DZM',
  'Sovie Konda': 'KpMA/SZC/KDA',
  'Sovie Kudzra': 'KpMA/SZC/KDK',
  'Sovie Nukofikordi': 'KpMA/SZC/NKD',
  'Sovie Nyamadzeanri': 'KpMA/SZC/NDN',
  'Sovie Tokoe': 'KpMA/SZC/TKE',
  'Sovie Tudzi': 'KpMA/SZC/TDZ',
  'Kpando Zongo': 'KpMA/SZC/ZGO',
};
