export const RENT_PT_OPTIONS = [
  'Bill boards',
  'Assembly Hall',
  'Assembly Conference Room',
  'Community Centres',
  'Sub-district/Metro Halls',
  'Assembly Forecourt',
  'Others',
  'Stores',
  'Stalls',
  'Sheds',
  'Rent of Open Market Space',
  'Rent of Market Warehouse',
  'Rent of Undeveloped Lands',
  'Hiring of Parks',
  'Rent on Leased Buildings',
  'Rent for Vendor Stands',
  'Official Residence',
  'Guest House',
  'Restaurant/Canteen',
  'Club House',
  'Stadium',
] as const;

export const RENT_PT_CODE_MAP: Record<string, string> = {
  'Bill boards':                   'KpMA/KZC/DBB/KPD/',
  'Assembly Hall':                 'KpMA/KZC/ASH/KPD/',
  'Assembly Conference Room':      'KpMA/KZC/ACR/KPD/',
  'Community Centres':             'KpMA/KZC/CCH/KPD/',
  'Sub-district/Metro Halls':      'KpMA/KZC/SDH/KPD/',
  'Assembly Forecourt':            'KpMA/KZC/AFC/KPD/',
  'Others':                        'KpMA/KZC/OTH/KPD/',
  'Stores':                        'KpMA/KZC/LKS/MKS/',
  'Stalls':                        'KpMA/KZC/MKT/STL/',
  'Sheds':                         'KpMA/KZC/MKT/SHD/',
  'Rent of Open Market Space':     'KpMA/KZC/MKT/OPS/',
  'Rent of Market Warehouse':      'KpMA/KZC/MKT/MWH/',
  'Rent of Undeveloped Lands':     'KpMA/KZC/RUL/KPD/',
  'Hiring of Parks':               'KpMA/KZC/HPK/KPD/',
  'Rent on Leased Buildings':      'KpMA/KZC/RLB/KPD/',
  'Rent for Vendor Stands':        'KpMA/KZC/RVS/KPD/',
  'Official Residence':            'KpMA/KZC/BGL/KPD/',
  'Guest House':                   'KpMA/KZC/GHR/KPD/',
  'Restaurant/Canteen':            'KpMA/KZC/RCR/KPD/',
  'Club House':                    'KpMA/KZC/CHR/KPD/',
  'Stadium':                       'KpMA/KZC/SSR/KPD/',
};
